import type { Theme } from "../types";

export const draftDefault: Theme = {
  id: "draft-default",
  name: "Draft Default",
  description: "Fast. Quiet. Powerful. AI is inside, not on top.",
  editorTheme: { dark: "atomone", light: "atomone" },
  variants: {
    light: {},
    dark: {
      colors: {
        background: "#0d0d0d",
        foreground: "#f5f5f5",
        card: "#1a1a1a",
        cardForeground: "#f5f5f5",
        popover: "#161616",
        popoverForeground: "#f5f5f5",
        primary: "#4a9eff",
        primaryForeground: "#ffffff",
        secondary: "#1a1a1a",
        secondaryForeground: "#aaaaaa",
        muted: "#161616",
        mutedForeground: "#7a7a7a",
        accent: "#1e1e1e",
        accentForeground: "#f5f5f5",
        destructive: "#ff6b35",
        border: "#2a2a2a",
        input: "#2a2a2a",
        ring: "#4a9eff",
        sidebar: "#111111",
        sidebarForeground: "#aaaaaa",
        sidebarPrimary: "#4a9eff",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#1a1a1a",
        sidebarAccentForeground: "#f5f5f5",
        sidebarBorder: "#2a2a2a",
        sidebarRing: "#4a9eff",
        radius: "4px",
      },
      terminal: {
        background: "#0d0d0d",
        foreground: "#f5f5f5",
        cursor: "#4a9eff",
        cursorAccent: "#0d0d0d",
        selection: "rgba(74, 158, 255, 0.2)",
      },
    },
  },
};
